sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-progress

script:
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
